#!/bin/sh

DEFAULT="\033[0m"
RED="\033[31m"
GREEN="\033[32m"

OK=$GREEN"[BTEST OK ]"$DEFAULT
NG=$RED"[BTEST NG ]"$DEFAULT

if getopts e OPT; then
    ERR="TRUE"
else
    ERR="FALSE"
fi
shift `expr $OPTIND - 1`
eval $@

if test $? -eq 0; then
    if [ $ERR = "FALSE" ]; then
        echo $OK $GREEN$@$DEFAULT
        exit 0
    else
        echo $NG $GREEN$@$DEFAULT
        exit 1
    fi
else
    if [ $ERR = "TRUE" ]; then
        echo $OK $RED$@$DEFAULT
        exit 0
    else
        echo $NG $RED$@$DEFAULT
        exit 1
    fi
fi
