#!/usr/bin/ruby

require "yaml"

$data = YAML.load(ARGF.read())

RED = 31
GREEN = 32

def colorize(text, color)
  "\e[#{color}m#{text}\e[0m"
end

def count(status)
  if $data[status].instance_of?(Array) then
    return $data[status].length
  else
    return 0
  end
end

def test(status)
  return 0 if !$data[status].instance_of?(Array)

  ng = 0
  for cmd in $data[status] do
    puts colorize("[BTEST RUN] ", GREEN) + cmd
    if (status == "success") then
      option = ""
    elsif (status == "error") then
      option = "-e "
    else
      assert(false)
    end
    IO.popen(
      File.dirname(__FILE__) + "/btest-each " + option + cmd
    ) {|io|
      puts io.readlines
    }
    if ($?.exitstatus == 1) then
      ng += 1
    end
  end
  return ng
end

total = count("success") + count("error")
ng = test("success") + test("error")
ok = total - ng
sum = "[BTEST SUM] OK " + ok.to_s + " NG " + ng.to_s

puts
if ng > 0 then
  puts colorize(sum, RED)
  exit 1
else
  puts colorize(sum, GREEN)
  exit 0
end
